name: deployment-workflow

on:
  push:
    branches:
    - main
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      id: install
      
    - run: ls
    - run: kubectl get pods
